image = "/capstor/store/cscs/swissai/infra01/container-images/evals-vllm-9-0-1.sqsh"

mounts = ["/capstor", "/iopsstor", "/users"]
workdir = "/workspace"

[annotations]
com.hooks.aws_ofi_nccl.enabled = "true"
com.hooks.aws_ofi_nccl.variant = "cuda12"
